### PR TITLE
1

### PR DESCRIPTION
**Pull request by zzim2x**

### CODE REVIEW

**Comment by zzim2x** [comment]
@outsideris: GitHub didn't allow me to assign the following users: outsideris.

Note that only [zzim2x members](https://github.com/orgs/zzim2x/people) and repo collaborators can be assigned.

<details>

In response to [this](https://github.com/zzim2x/test/pull/2#issuecomment-409150942):

>/assign outsideris


Instructions for interacting with me using PR comments are available [here](https://git.k8s.io/community/contributors/guide/pull-requests.md).  If you have questions or suggestions related to my behavior, please file an issue against the [kubernetes/test-infra](https://github.com/kubernetes/test-infra/issues/new?title=Prow%20issue:) repository.
</details>

**Comment by zzim2x** [comment]
APPROVE

**Comment by zzim2x** [comment]
LGTM

**Comment by zzim2x** [comment]
[APPROVALNOTIFIER] This PR is **NOT APPROVED**

This pull-request has been approved by: *<a href="https://github.com/zzim2x/test/pull/2#issuecomment-409151403" title="Approved">outsideris</a>*, *<a href="https://github.com/zzim2x/test/pull/2#" title="Author self-approved">zzim2x</a>*
To fully approve this pull request, please assign additional approvers.
We suggest the following additional approvers: 

Assign the PR to them by writing `/assign ` in a comment when ready.

The full list of commands accepted by this bot can be found [here](https://go.k8s.io/bot-commands).

The pull request process is described [here](https://git.k8s.io/community/contributors/guide/owners.md#the-code-review-process)

<details open>
Needs approval from an approver in each of these files:

- **[OWNERS](https://github.com/zzim2x/test/blob/master/OWNERS)**

Approvers can indicate their approval by writing `/approve` in a comment
Approvers can cancel approval by writing `/approve cancel` in a comment
</details>

**Comment by zzim2x** [comment]
@outsideris: changing LGTM is restricted to assignees, and only zzim2x/test repo collaborators may be assigned issues.

<details>

In response to [this](https://github.com/zzim2x/test/pull/2#issuecomment-409151635):

>/lgtm


Instructions for interacting with me using PR comments are available [here](https://git.k8s.io/community/contributors/guide/pull-requests.md).  If you have questions or suggestions related to my behavior, please file an issue against the [kubernetes/test-infra](https://github.com/kubernetes/test-infra/issues/new?title=Prow%20issue:) repository.
</details>

**Comment by zzim2x** [comment]
LGTM

**Comment by zzim2x** [comment]
[APPROVALNOTIFIER] This PR is **NOT APPROVED**

This pull-request has been approved by: *<a href="https://github.com/zzim2x/test/pull/2#issuecomment-409151635" title="LGTM">outsideris</a>*, *<a href="https://github.com/zzim2x/test/pull/2#" title="Author self-approved">zzim2x</a>*
To fully approve this pull request, please assign additional approvers.
We suggest the following additional approvers: 

Assign the PR to them by writing `/assign ` in a comment when ready.

The full list of commands accepted by this bot can be found [here](https://go.k8s.io/bot-commands).

The pull request process is described [here](https://git.k8s.io/community/contributors/guide/owners.md#the-code-review-process)

<details open>
Needs approval from an approver in each of these files:

- **[OWNERS](https://github.com/zzim2x/test/blob/master/OWNERS)**

Approvers can indicate their approval by writing `/approve` in a comment
Approvers can cancel approval by writing `/approve cancel` in a comment
</details>

**Comment by zzim2x** [comment]
LGTM

**Comment by zzim2x** [comment]
@outsideris: 
	This request has been marked as needing help from a contributor.

Please ensure the request meets the requirements listed [here](https://git.k8s.io/community/contributors/devel/help-wanted.md).

If this request no longer meets these requirements, the label can be removed
by commenting with the `/remove-help` command.


<details>

In response to [this](https://github.com/zzim2x/test/pull/2):

>/help


Instructions for interacting with me using PR comments are available [here](https://git.k8s.io/community/contributors/guide/pull-requests.md).  If you have questions or suggestions related to my behavior, please file an issue against the [kubernetes/test-infra](https://github.com/kubernetes/test-infra/issues/new?title=Prow%20issue:) repository.
</details>

**Comment by zzim2x** [comment]
@outsideris: I dreamed about drowning in an ocean made out of orange soda last night. It took me a while to work out it was just a Fanta sea.

<details>

In response to [this](https://github.com/zzim2x/test/pull/2#issuecomment-409152407):

>/joke


Instructions for interacting with me using PR comments are available [here](https://git.k8s.io/community/contributors/guide/pull-requests.md).  If you have questions or suggestions related to my behavior, please file an issue against the [kubernetes/test-infra](https://github.com/kubernetes/test-infra/issues/new?title=Prow%20issue:) repository.
</details>

**Comment by outsideris** [comment]
(저게 농담인건가?)

**Comment by zzim2x** [comment]
@anarcher: Did you hear about the Mexican train killer? He had loco motives

<details>

In response to [this](https://github.com/zzim2x/test/pull/2#issuecomment-409154608):

>/joke 


Instructions for interacting with me using PR comments are available [here](https://git.k8s.io/community/contributors/guide/pull-requests.md).  If you have questions or suggestions related to my behavior, please file an issue against the [kubernetes/test-infra](https://github.com/kubernetes/test-infra/issues/new?title=Prow%20issue:) repository.
</details>

**Comment by zzim2x** [comment]
@anarcher: GitHub didn't allow me to assign the following users: outsideris.

Note that only [zzim2x members](https://github.com/orgs/zzim2x/people) and repo collaborators can be assigned.

<details>

In response to [this](https://github.com/zzim2x/test/pull/2#issuecomment-409154681):

>/assign outsideris 


Instructions for interacting with me using PR comments are available [here](https://git.k8s.io/community/contributors/guide/pull-requests.md).  If you have questions or suggestions related to my behavior, please file an issue against the [kubernetes/test-infra](https://github.com/kubernetes/test-infra/issues/new?title=Prow%20issue:) repository.
</details>

**Pull request merged**
